### ISSUE TITLE
Imbue V1 

### ISSUE THREAD

**Issue by f-gate** [ImbueNetwork/imbue#211]
Tracking issue for the first full release of Imbue collator:

Devops
- [ ] https://github.com/ImbueNetwork/imbue/issues/210

Milestones
- [ ] https://github.com/ImbueNetwork/imbue/issues/193
- [ ] https://github.com/ImbueNetwork/imbue/issues/196
- [ ] https://github.com/ImbueNetwork/imbue/issues/199
- [ ] https://github.com/ImbueNetwork/imbue/issues/209

Briefs
- [ ] https://github.com/ImbueNetwork/imbue/issues/192

Disputes
- [ ] https://github.com/ImbueNetwork/imbue/issues/131

Integration of Disputes and Fellowship: 
- [ ] todo after the above has been completed
