### ISSUE TITLE
Stop using contributions as votes for milestones

### ISSUE THREAD

**Issue by f-gate** [ImbueNetwork/imbue#266]
it just does make sense anymore with the introduction of grants, where an approver is a contributor yet hasnt contributed. 
The state should make sense, it currently doesnt.

What is needed to change?

- [ ] Add `approvers` which are the accounts responsible for approving milestones. We must also have a `vote_weight` (the same as before).

- [ ] Remove the concept of 'contributor'. In fact this is not needed at all due to the introduction of multi chain `refund_locations` in the config.

- [ ] In pallet grants, then we can say that we have 'approvers' not contributors and just specify the `TreasuryOrigin` on instantiation to handle refunds.

- [ ] Alas in vote_on_milestone refactor the terminology
