### ISSUE TITLE
Refactor for Milestone Pallet Epic

### ISSUE THREAD

**Issue by f-gate** [ImbueNetwork/imbue#84]
Currently we have a very rigid structure that is heavily reliant on the proposals pallet. 
Now we are expanding functionality which depend on milestones we need to move said logic into its own pallet.
This would mean the pallet-proposals, pallet-briefs and the new pallet-grants will all be dependent on pallet-milestones.

The 3 pallets mentioned will be a route to milestone submission and not contain any milestone submission logic at all.
Making milestones generic also allows the dispute pallet to be built alot more streamlined.

- [ ] Create the new milestone pallet
- [ ] Remove milestone logic from proposals
- [ ] Remove refund logic from proposals
- [x] Change the BriefEvolver trait into a IntoMilestone thing (and add a hashing method)
- [ ] Make milestones generic over some hash
- [ ] Revive tests in proposals
